module_order: # the order the modules of this case should be executed
              # typically, this should be pvsystem -> grid -> utiltiy -> others
              # see https://nrel-pysam.readthedocs.io/en/master/Configs.html?highlight=belpe#sam-simulation-configurations
  - Pvwattsv7
  - Grid
  - Utilityrate5
  - Cashloan

num_realizations: 2 # number of passes to make
num_combiners: 2 # total number of DC combiner boxes
num_transformers: 1 # total number of Transformers
num_trackers: 2 # total number of trackers
