name: black-checker

on:
  pull_request:
    types: [opened]
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          options: "--line-length 120 --target-version py39 --check"
          src: "."
