name: tagged-release

on:
  push:
    tags:
      - "v*"
    branches:
      - "v*"

jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
          architecture: "x64"
      - run: mkdir build && pip install wheel && pip wheel . -w build/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.7.6"
          prerelease: false
          files: |
            build/pvrpm-*.whl
