name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - run: mkdir build && pip install wheel && pip wheel . -w build/ --use-feature=in-tree-build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/pvrpm-*.whl
