name: pytest

on:
  pull_request:
    types: [opened]
  push:

jobs:
  pytest-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
          architecture: "x64"
      - run: pip install .[testing] && pytest
